name = "andesaware-ecowitt"
main = "src/index.js"
compatibility_date = "2025-01-01"

routes = [{ pattern = "api.andesaware.com/weatherstation/*", zone_name = "andesaware.com" }]

[[kv_namespaces]]
binding = "WEATHER_KV"
id = "ab86dc440d124205add2197b83bfcefd"

[triggers]
crons = ["*/5 * * * *"]  # Every 5 minutes